### ISSUE TITLE
Environment forces me to use url "laravel.test" by default

### ISSUE THREAD

**Issue by ndroo** [ryoluo/sail-ssl#3]
How does one revert this back to localhost? this change wasnt mentioned in the readme and breaks my local.

**Comment by ryoluo** [comment]
You can publish Nginx configuration file by this command:
```bash
$ php artisan sail-ssl:publish
```
Then you can change `server_name` directive
### nginx/templates/default.conf.template
```nginx
server {
    listen  80  default_server;
    server_name laravel.test;

    return  301 https://$host:${SSL_PORT}$request_uri;
}

server {
    listen  443 ssl default_server;
    server_name laravel.test;

    # Self signed certificates
    # Don't use them in a production server!
    ssl_certificate     /etc/nginx/certs/server.pem;
    ssl_certificate_key /etc/nginx/certs/server.key;

    location / {
        proxy_pass	http://laravel.test;
    }
}
```

**Comment by waiaryi** [comment]
Another alternative that I think would be reasonable, not to have a folder in the project root that would only be used in development environments and not be omitting it in .gitignore, it would be to pass through an environment variable the value of the virtual host. In this way, the default configuration of the ```docker-compose.yml``` file is maintained.
In my case, I used the same ```APP_SERVER``` environment variable that Sail uses to refer to the virtual host, I passed it to the template of the NGINX configuration.

### ./.env
```
APP_SERVICE=anis.test
```

### ./docker-compose.yml

```yml
services:
    nginx:
        environment:
            - SSL_PORT=${SSL_PORT:-443}
            - APP_SERVICE=${APP_SERVICE:-laravel.test}
    anis.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        ....
```

### nginx/templates/default.conf.template
```nginx
server {
    listen  80  default_server;
    server_name localhost;

    return  301 https://$host:${SSL_PORT}$request_uri;
}

server {
    listen  443 ssl default_server;
    server_name localhost;

    # Self signed certificates
    # Don't use them in a production server!
    ssl_certificate     /etc/nginx/certs/server.pem;
    ssl_certificate_key /etc/nginx/certs/server.key;

    location / {
        proxy_pass	http://${APP_SERVICE};
    }
}
```
